# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    # command: --serviceExecutor adaptive
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

      ME_CONFIG_MONGODB_URL: mongodb://user:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: true